### ISSUE TITLE
pip install -r requirements.txt 

### ISSUE THREAD

**Issue by wangjinyang** [ox0spy/RomanHitman#4]
Requirement already satisfied: python-magic in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Collecting pyliblzma (from -r requirements.txt (line 3))
  Using cached pyliblzma-0.5.3.tar.bz2
Installing collected packages: python-lzo, pyliblzma
  Running setup.py install for python-lzo ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kt/7c31pyxx4gb0b2rx88955ycm0000gn/T/pip-build-EzFDiq/python-lzo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/kt/7c31pyxx4gb0b2rx88955ycm0000gn/T/pip-Yx4kQb-record/install-record.txt --single-version-externally-managed --compile:
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:251: UserWarning: 'licence' distribution option is deprecated; use 'license'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'lzo' extension
    creating build
    creating build/temp.macosx-10.12-intel-2.7
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/usr/include/lzo -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c lzomodule.c -o build/temp.macosx-10.12-intel-2.7/lzomodule.o
    lzomodule.c:35:10: fatal error: 'lzo1x.h' file not found
    #include <lzo1x.h>
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kt/7c31pyxx4gb0b2rx88955ycm0000gn/T/pip-build-EzFDiq/python-lzo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/kt/7c31pyxx4gb0b2rx88955ycm0000gn/T/pip-Yx4kQb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kt/7c31pyxx4gb0b2rx88955ycm0000gn/T/pip-build-EzFDiq/python-lzo/

**Comment by zh4n7wm** [comment]
https://github.com/jd-boyd/python-lzo/issues/23
  
自己搜下 `'lzo1x.h' file not found` 的原因，也许有些库没有正确安装，或者安装了但编译系统没有找到。
